project_id = "gmlwpcadioqwqirplxlo"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-booking-accepted]
verify_jwt = false

[functions.send-booking-rejected]
verify_jwt = false
