project_id = "gmlwpcadioqwqirplxlo"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-booking-accepted]
verify_jwt = false

[functions.send-booking-rejected]
verify_jwt = false

[functions.send-feedback-notification]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false
